package com.doubleclue.dcup.logic;

public enum ActionItem {

	OTP_ADD_ACTION,
	OTP_DELETE_ACTION,
	OTP_DISABLE_ACTION,
	OTP_ENABLE_ACTION,

	NETWORK_DEVICE_ADD_ACTION,
	NETWORK_DEVICE_ENABLE_ACTION,
	NETWORK_DEVICE_DISABLE_ACTION,
	NETWORK_DEVICE_DELETE_ACTION,

	FIDO_ADD_ACTION,
	FIDO_DELETE_ACTION,

//	CLOUD_SAFE_UPLOAD,
//	CLOUD_SAFE_DOWNLOAD,
//	CLOUD_SAFE_DELETE,
	
	CLOUD_SAFE_SHARE_FILE_ACTION,

	SAVE_PROFIL_ACTION,
	
//	SHARED_CLOUD_SAFE_UPLOAD,
//	SHARED_CLOUD_SAFE_DOWNLOAD
}
