/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class AuthUserParam : TBase
{
  private string _authGatewayId;
  private string _loginId;
  private ThriftAuthMethod _authMethod;
  private byte[] _encPassword;
  private byte[] _encPasscode;
  private byte[] _sharedSecret;
  private byte[] _udid;
  private string _workstationName;
  private ClientType _clientType;
  private Dictionary<string, string> _propertyMap;

  public string AuthGatewayId
  {
    get
    {
      return _authGatewayId;
    }
    set
    {
      __isset.authGatewayId = true;
      this._authGatewayId = value;
    }
  }

  public string LoginId
  {
    get
    {
      return _loginId;
    }
    set
    {
      __isset.loginId = true;
      this._loginId = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref=".ThriftAuthMethod"/>
  /// </summary>
  public ThriftAuthMethod AuthMethod
  {
    get
    {
      return _authMethod;
    }
    set
    {
      __isset.authMethod = true;
      this._authMethod = value;
    }
  }

  public byte[] EncPassword
  {
    get
    {
      return _encPassword;
    }
    set
    {
      __isset.encPassword = true;
      this._encPassword = value;
    }
  }

  public byte[] EncPasscode
  {
    get
    {
      return _encPasscode;
    }
    set
    {
      __isset.encPasscode = true;
      this._encPasscode = value;
    }
  }

  public byte[] SharedSecret
  {
    get
    {
      return _sharedSecret;
    }
    set
    {
      __isset.sharedSecret = true;
      this._sharedSecret = value;
    }
  }

  public byte[] Udid
  {
    get
    {
      return _udid;
    }
    set
    {
      __isset.udid = true;
      this._udid = value;
    }
  }

  public string WorkstationName
  {
    get
    {
      return _workstationName;
    }
    set
    {
      __isset.workstationName = true;
      this._workstationName = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref=".ClientType"/>
  /// </summary>
  public ClientType ClientType
  {
    get
    {
      return _clientType;
    }
    set
    {
      __isset.clientType = true;
      this._clientType = value;
    }
  }

  public Dictionary<string, string> PropertyMap
  {
    get
    {
      return _propertyMap;
    }
    set
    {
      __isset.propertyMap = true;
      this._propertyMap = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool authGatewayId;
    public bool loginId;
    public bool authMethod;
    public bool encPassword;
    public bool encPasscode;
    public bool sharedSecret;
    public bool udid;
    public bool workstationName;
    public bool clientType;
    public bool propertyMap;
  }

  public AuthUserParam() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              AuthGatewayId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              LoginId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              AuthMethod = (ThriftAuthMethod)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              EncPassword = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              EncPasscode = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              SharedSecret = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              Udid = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.String) {
              WorkstationName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I32) {
              ClientType = (ClientType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.Map) {
              {
                PropertyMap = new Dictionary<string, string>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  string _key2;
                  string _val3;
                  _key2 = iprot.ReadString();
                  _val3 = iprot.ReadString();
                  PropertyMap[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("AuthUserParam");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AuthGatewayId != null && __isset.authGatewayId) {
        field.Name = "authGatewayId";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AuthGatewayId);
        oprot.WriteFieldEnd();
      }
      if (LoginId != null && __isset.loginId) {
        field.Name = "loginId";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(LoginId);
        oprot.WriteFieldEnd();
      }
      if (__isset.authMethod) {
        field.Name = "authMethod";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)AuthMethod);
        oprot.WriteFieldEnd();
      }
      if (EncPassword != null && __isset.encPassword) {
        field.Name = "encPassword";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(EncPassword);
        oprot.WriteFieldEnd();
      }
      if (EncPasscode != null && __isset.encPasscode) {
        field.Name = "encPasscode";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(EncPasscode);
        oprot.WriteFieldEnd();
      }
      if (SharedSecret != null && __isset.sharedSecret) {
        field.Name = "sharedSecret";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(SharedSecret);
        oprot.WriteFieldEnd();
      }
      if (Udid != null && __isset.udid) {
        field.Name = "udid";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Udid);
        oprot.WriteFieldEnd();
      }
      if (WorkstationName != null && __isset.workstationName) {
        field.Name = "workstationName";
        field.Type = TType.String;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(WorkstationName);
        oprot.WriteFieldEnd();
      }
      if (__isset.clientType) {
        field.Name = "clientType";
        field.Type = TType.I32;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)ClientType);
        oprot.WriteFieldEnd();
      }
      if (PropertyMap != null && __isset.propertyMap) {
        field.Name = "propertyMap";
        field.Type = TType.Map;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, PropertyMap.Count));
          foreach (string _iter4 in PropertyMap.Keys)
          {
            oprot.WriteString(_iter4);
            oprot.WriteString(PropertyMap[_iter4]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("AuthUserParam(");
    bool __first = true;
    if (AuthGatewayId != null && __isset.authGatewayId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AuthGatewayId: ");
      __sb.Append(AuthGatewayId);
    }
    if (LoginId != null && __isset.loginId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("LoginId: ");
      __sb.Append(LoginId);
    }
    if (__isset.authMethod) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AuthMethod: ");
      __sb.Append(AuthMethod);
    }
    if (EncPassword != null && __isset.encPassword) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("EncPassword: ");
      __sb.Append(EncPassword);
    }
    if (EncPasscode != null && __isset.encPasscode) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("EncPasscode: ");
      __sb.Append(EncPasscode);
    }
    if (SharedSecret != null && __isset.sharedSecret) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("SharedSecret: ");
      __sb.Append(SharedSecret);
    }
    if (Udid != null && __isset.udid) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Udid: ");
      __sb.Append(Udid);
    }
    if (WorkstationName != null && __isset.workstationName) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("WorkstationName: ");
      __sb.Append(WorkstationName);
    }
    if (__isset.clientType) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ClientType: ");
      __sb.Append(ClientType);
    }
    if (PropertyMap != null && __isset.propertyMap) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("PropertyMap: ");
      __sb.Append(PropertyMap);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

