/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class AuthSelectResponse : TBase
{
  private List<ThriftAuthMethod> _authMethods;

  public List<ThriftAuthMethod> AuthMethods
  {
    get
    {
      return _authMethods;
    }
    set
    {
      __isset.authMethods = true;
      this._authMethods = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool authMethods;
  }

  public AuthSelectResponse() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                AuthMethods = new List<ThriftAuthMethod>();
                TList _list9 = iprot.ReadListBegin();
                for( int _i10 = 0; _i10 < _list9.Count; ++_i10)
                {
                  ThriftAuthMethod _elem11;
                  _elem11 = (ThriftAuthMethod)iprot.ReadI32();
                  AuthMethods.Add(_elem11);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("AuthSelectResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AuthMethods != null && __isset.authMethods) {
        field.Name = "authMethods";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I32, AuthMethods.Count));
          foreach (ThriftAuthMethod _iter12 in AuthMethods)
          {
            oprot.WriteI32((int)_iter12);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("AuthSelectResponse(");
    bool __first = true;
    if (AuthMethods != null && __isset.authMethods) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AuthMethods: ");
      __sb.Append(AuthMethods);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

