/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ClientType
{
  ANDROID = 0,
  I_OS = 1,
  WINDOWS = 2,
  MAC = 3,
  Linux = 4,
}
