/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


/// <summary>
/// Thrift also lets you define constants for use across languages. Complex
/// types and structs are specified using JSON notation.
/// </summary>
#if !SILVERLIGHT
[Serializable]
#endif
public partial class ServerSignatureParam : TBase
{
  private byte[] _dataForSignature;
  private AppVersion _appVersion;
  private AppVersion _libVersion;
  private string _domainName;
  private bool _iamDcem;
  private CommClientType _commClientType;

  public byte[] DataForSignature
  {
    get
    {
      return _dataForSignature;
    }
    set
    {
      __isset.dataForSignature = true;
      this._dataForSignature = value;
    }
  }

  public AppVersion AppVersion
  {
    get
    {
      return _appVersion;
    }
    set
    {
      __isset.appVersion = true;
      this._appVersion = value;
    }
  }

  public AppVersion LibVersion
  {
    get
    {
      return _libVersion;
    }
    set
    {
      __isset.libVersion = true;
      this._libVersion = value;
    }
  }

  public string DomainName
  {
    get
    {
      return _domainName;
    }
    set
    {
      __isset.domainName = true;
      this._domainName = value;
    }
  }

  public bool IamDcem
  {
    get
    {
      return _iamDcem;
    }
    set
    {
      __isset.iamDcem = true;
      this._iamDcem = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref=".CommClientType"/>
  /// </summary>
  public CommClientType CommClientType
  {
    get
    {
      return _commClientType;
    }
    set
    {
      __isset.commClientType = true;
      this._commClientType = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool dataForSignature;
    public bool appVersion;
    public bool libVersion;
    public bool domainName;
    public bool iamDcem;
    public bool commClientType;
  }

  public ServerSignatureParam() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              DataForSignature = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              AppVersion = new AppVersion();
              AppVersion.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              LibVersion = new AppVersion();
              LibVersion.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              DomainName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Bool) {
              IamDcem = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              CommClientType = (CommClientType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ServerSignatureParam");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (DataForSignature != null && __isset.dataForSignature) {
        field.Name = "dataForSignature";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(DataForSignature);
        oprot.WriteFieldEnd();
      }
      if (AppVersion != null && __isset.appVersion) {
        field.Name = "appVersion";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        AppVersion.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (LibVersion != null && __isset.libVersion) {
        field.Name = "libVersion";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        LibVersion.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (DomainName != null && __isset.domainName) {
        field.Name = "domainName";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(DomainName);
        oprot.WriteFieldEnd();
      }
      if (__isset.iamDcem) {
        field.Name = "iamDcem";
        field.Type = TType.Bool;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IamDcem);
        oprot.WriteFieldEnd();
      }
      if (__isset.commClientType) {
        field.Name = "commClientType";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)CommClientType);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ServerSignatureParam(");
    bool __first = true;
    if (DataForSignature != null && __isset.dataForSignature) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("DataForSignature: ");
      __sb.Append(DataForSignature);
    }
    if (AppVersion != null && __isset.appVersion) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AppVersion: ");
      __sb.Append(AppVersion== null ? "<null>" : AppVersion.ToString());
    }
    if (LibVersion != null && __isset.libVersion) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("LibVersion: ");
      __sb.Append(LibVersion== null ? "<null>" : LibVersion.ToString());
    }
    if (DomainName != null && __isset.domainName) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("DomainName: ");
      __sb.Append(DomainName);
    }
    if (__isset.iamDcem) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("IamDcem: ");
      __sb.Append(IamDcem);
    }
    if (__isset.commClientType) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("CommClientType: ");
      __sb.Append(CommClientType);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

