CD ..
set INSTALLATION_PATH=%CD%
"%INSTALLATION_PATH%\jvm\bin\java" -DDCEM_HOME="%INSTALLATION_PATH%\DCEM_HOME" -DINSTALLATION_PATH="%INSTALLATION_PATH%" -DdebugLog=false -Dlog4jdbc=false -jar "%INSTALLATION_PATH%\PortalDemo.jar"
EXIT /B %ERRORLEVEL%


