package com.doubleclue.dcup.logic;

public enum ViewItem {
	CLOUD_DATA_VIEW , OTP_TOKEN_VIEW, NETWORK_DEVICE_VIEW, CHANGE_PASSWORD_VIEW, USER_PROFILE_VIEW, FIDO_VIEW,
	PASSWORD_MANAGER_DEPRECATED, PASSWORD_MANAGER;	
}
