/*
 * DoubleClue REST API
 * DoubleClue URL http://yourhost:8001/dcem/restApi/as
 *
 * OpenAPI spec version: 1.5.0
 * Contact: emanuel.galea@hws-gruppe.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.doubleclue.dcem.as.restapi.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AsApiShareCloudSafeDetails
 */

@SuppressWarnings("serial")
public class AsApiShareCloudSafeDetails implements Serializable {
	@JsonProperty("cloudSafeFile")
	private AsApiCloudSafeFile cloudSafeFile = null;

	@JsonProperty("writeAccess")
	private boolean writeAccess = false;
	

	/**
	 * Get cloudSafeFile
	 * @return cloudSafeFile
	 **/
	@JsonProperty("cloudSafeFile")
	public AsApiCloudSafeFile getCloudSafeFile() {
		return cloudSafeFile;
	}

	public void setCloudSafeFile(AsApiCloudSafeFile cloudSafeFile) {
		this.cloudSafeFile = cloudSafeFile;
	}

	/**
	 * Get writeAccess
	 * @return writeAccess
	 **/
	@JsonProperty("writeAccess")
	public boolean isWriteAccess() {
		return writeAccess;
	}

	public void setWriteAccess(boolean writeAccess) {
		this.writeAccess = writeAccess;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AsApiShareCloudSafeDetails asApiShareCloudSafeDetails = (AsApiShareCloudSafeDetails) o;
		return Objects.equals(this.cloudSafeFile, asApiShareCloudSafeDetails.cloudSafeFile)
				&& Objects.equals(this.writeAccess, asApiShareCloudSafeDetails.writeAccess);
	}

	@Override
	public int hashCode() {
		return Objects.hash(cloudSafeFile, writeAccess);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AsApiShareCloudSafeDetails {\n");

		sb.append("    cloudSafeFile: ").append(toIndentedString(cloudSafeFile)).append("\n");
		sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
