/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.doubleclue.comm.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-10-21")
public class RegisterDispatcherParam implements org.apache.thrift.TBase<RegisterDispatcherParam, RegisterDispatcherParam._Fields>, java.io.Serializable, Cloneable, Comparable<RegisterDispatcherParam> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RegisterDispatcherParam");

  private static final org.apache.thrift.protocol.TField DOMAIN_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("domainName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DISPATCHER_SIGNATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("dispatcherSignature", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PN_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("pnKey", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RegisterDispatcherParamStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RegisterDispatcherParamTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String domainName; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer dispatcherSignature; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String pnKey; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DOMAIN_NAME((short)1, "domainName"),
    DISPATCHER_SIGNATURE((short)2, "dispatcherSignature"),
    PN_KEY((short)3, "pnKey");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOMAIN_NAME
          return DOMAIN_NAME;
        case 2: // DISPATCHER_SIGNATURE
          return DISPATCHER_SIGNATURE;
        case 3: // PN_KEY
          return PN_KEY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOMAIN_NAME, new org.apache.thrift.meta_data.FieldMetaData("domainName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPATCHER_SIGNATURE, new org.apache.thrift.meta_data.FieldMetaData("dispatcherSignature", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PN_KEY, new org.apache.thrift.meta_data.FieldMetaData("pnKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RegisterDispatcherParam.class, metaDataMap);
  }

  public RegisterDispatcherParam() {
  }

  public RegisterDispatcherParam(
    java.lang.String domainName,
    java.nio.ByteBuffer dispatcherSignature,
    java.lang.String pnKey)
  {
    this();
    this.domainName = domainName;
    this.dispatcherSignature = org.apache.thrift.TBaseHelper.copyBinary(dispatcherSignature);
    this.pnKey = pnKey;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RegisterDispatcherParam(RegisterDispatcherParam other) {
    if (other.isSetDomainName()) {
      this.domainName = other.domainName;
    }
    if (other.isSetDispatcherSignature()) {
      this.dispatcherSignature = org.apache.thrift.TBaseHelper.copyBinary(other.dispatcherSignature);
    }
    if (other.isSetPnKey()) {
      this.pnKey = other.pnKey;
    }
  }

  public RegisterDispatcherParam deepCopy() {
    return new RegisterDispatcherParam(this);
  }

  @Override
  public void clear() {
    this.domainName = null;
    this.dispatcherSignature = null;
    this.pnKey = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDomainName() {
    return this.domainName;
  }

  public RegisterDispatcherParam setDomainName(@org.apache.thrift.annotation.Nullable java.lang.String domainName) {
    this.domainName = domainName;
    return this;
  }

  public void unsetDomainName() {
    this.domainName = null;
  }

  /** Returns true if field domainName is set (has been assigned a value) and false otherwise */
  public boolean isSetDomainName() {
    return this.domainName != null;
  }

  public void setDomainNameIsSet(boolean value) {
    if (!value) {
      this.domainName = null;
    }
  }

  public byte[] getDispatcherSignature() {
    setDispatcherSignature(org.apache.thrift.TBaseHelper.rightSize(dispatcherSignature));
    return dispatcherSignature == null ? null : dispatcherSignature.array();
  }

  public java.nio.ByteBuffer bufferForDispatcherSignature() {
    return org.apache.thrift.TBaseHelper.copyBinary(dispatcherSignature);
  }

  public RegisterDispatcherParam setDispatcherSignature(byte[] dispatcherSignature) {
    this.dispatcherSignature = dispatcherSignature == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(dispatcherSignature.clone());
    return this;
  }

  public RegisterDispatcherParam setDispatcherSignature(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer dispatcherSignature) {
    this.dispatcherSignature = org.apache.thrift.TBaseHelper.copyBinary(dispatcherSignature);
    return this;
  }

  public void unsetDispatcherSignature() {
    this.dispatcherSignature = null;
  }

  /** Returns true if field dispatcherSignature is set (has been assigned a value) and false otherwise */
  public boolean isSetDispatcherSignature() {
    return this.dispatcherSignature != null;
  }

  public void setDispatcherSignatureIsSet(boolean value) {
    if (!value) {
      this.dispatcherSignature = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPnKey() {
    return this.pnKey;
  }

  public RegisterDispatcherParam setPnKey(@org.apache.thrift.annotation.Nullable java.lang.String pnKey) {
    this.pnKey = pnKey;
    return this;
  }

  public void unsetPnKey() {
    this.pnKey = null;
  }

  /** Returns true if field pnKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPnKey() {
    return this.pnKey != null;
  }

  public void setPnKeyIsSet(boolean value) {
    if (!value) {
      this.pnKey = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DOMAIN_NAME:
      if (value == null) {
        unsetDomainName();
      } else {
        setDomainName((java.lang.String)value);
      }
      break;

    case DISPATCHER_SIGNATURE:
      if (value == null) {
        unsetDispatcherSignature();
      } else {
        if (value instanceof byte[]) {
          setDispatcherSignature((byte[])value);
        } else {
          setDispatcherSignature((java.nio.ByteBuffer)value);
        }
      }
      break;

    case PN_KEY:
      if (value == null) {
        unsetPnKey();
      } else {
        setPnKey((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DOMAIN_NAME:
      return getDomainName();

    case DISPATCHER_SIGNATURE:
      return getDispatcherSignature();

    case PN_KEY:
      return getPnKey();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DOMAIN_NAME:
      return isSetDomainName();
    case DISPATCHER_SIGNATURE:
      return isSetDispatcherSignature();
    case PN_KEY:
      return isSetPnKey();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RegisterDispatcherParam)
      return this.equals((RegisterDispatcherParam)that);
    return false;
  }

  public boolean equals(RegisterDispatcherParam that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_domainName = true && this.isSetDomainName();
    boolean that_present_domainName = true && that.isSetDomainName();
    if (this_present_domainName || that_present_domainName) {
      if (!(this_present_domainName && that_present_domainName))
        return false;
      if (!this.domainName.equals(that.domainName))
        return false;
    }

    boolean this_present_dispatcherSignature = true && this.isSetDispatcherSignature();
    boolean that_present_dispatcherSignature = true && that.isSetDispatcherSignature();
    if (this_present_dispatcherSignature || that_present_dispatcherSignature) {
      if (!(this_present_dispatcherSignature && that_present_dispatcherSignature))
        return false;
      if (!this.dispatcherSignature.equals(that.dispatcherSignature))
        return false;
    }

    boolean this_present_pnKey = true && this.isSetPnKey();
    boolean that_present_pnKey = true && that.isSetPnKey();
    if (this_present_pnKey || that_present_pnKey) {
      if (!(this_present_pnKey && that_present_pnKey))
        return false;
      if (!this.pnKey.equals(that.pnKey))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDomainName()) ? 131071 : 524287);
    if (isSetDomainName())
      hashCode = hashCode * 8191 + domainName.hashCode();

    hashCode = hashCode * 8191 + ((isSetDispatcherSignature()) ? 131071 : 524287);
    if (isSetDispatcherSignature())
      hashCode = hashCode * 8191 + dispatcherSignature.hashCode();

    hashCode = hashCode * 8191 + ((isSetPnKey()) ? 131071 : 524287);
    if (isSetPnKey())
      hashCode = hashCode * 8191 + pnKey.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RegisterDispatcherParam other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDomainName()).compareTo(other.isSetDomainName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDomainName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.domainName, other.domainName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDispatcherSignature()).compareTo(other.isSetDispatcherSignature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDispatcherSignature()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dispatcherSignature, other.dispatcherSignature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPnKey()).compareTo(other.isSetPnKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPnKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pnKey, other.pnKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RegisterDispatcherParam(");
    boolean first = true;

    sb.append("domainName:");
    if (this.domainName == null) {
      sb.append("null");
    } else {
      sb.append(this.domainName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dispatcherSignature:");
    if (this.dispatcherSignature == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.dispatcherSignature, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pnKey:");
    if (this.pnKey == null) {
      sb.append("null");
    } else {
      sb.append(this.pnKey);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RegisterDispatcherParamStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RegisterDispatcherParamStandardScheme getScheme() {
      return new RegisterDispatcherParamStandardScheme();
    }
  }

  private static class RegisterDispatcherParamStandardScheme extends org.apache.thrift.scheme.StandardScheme<RegisterDispatcherParam> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RegisterDispatcherParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DOMAIN_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.domainName = iprot.readString();
              struct.setDomainNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DISPATCHER_SIGNATURE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dispatcherSignature = iprot.readBinary();
              struct.setDispatcherSignatureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PN_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pnKey = iprot.readString();
              struct.setPnKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RegisterDispatcherParam struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.domainName != null) {
        oprot.writeFieldBegin(DOMAIN_NAME_FIELD_DESC);
        oprot.writeString(struct.domainName);
        oprot.writeFieldEnd();
      }
      if (struct.dispatcherSignature != null) {
        oprot.writeFieldBegin(DISPATCHER_SIGNATURE_FIELD_DESC);
        oprot.writeBinary(struct.dispatcherSignature);
        oprot.writeFieldEnd();
      }
      if (struct.pnKey != null) {
        oprot.writeFieldBegin(PN_KEY_FIELD_DESC);
        oprot.writeString(struct.pnKey);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RegisterDispatcherParamTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RegisterDispatcherParamTupleScheme getScheme() {
      return new RegisterDispatcherParamTupleScheme();
    }
  }

  private static class RegisterDispatcherParamTupleScheme extends org.apache.thrift.scheme.TupleScheme<RegisterDispatcherParam> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RegisterDispatcherParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDomainName()) {
        optionals.set(0);
      }
      if (struct.isSetDispatcherSignature()) {
        optionals.set(1);
      }
      if (struct.isSetPnKey()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetDomainName()) {
        oprot.writeString(struct.domainName);
      }
      if (struct.isSetDispatcherSignature()) {
        oprot.writeBinary(struct.dispatcherSignature);
      }
      if (struct.isSetPnKey()) {
        oprot.writeString(struct.pnKey);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RegisterDispatcherParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.domainName = iprot.readString();
        struct.setDomainNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.dispatcherSignature = iprot.readBinary();
        struct.setDispatcherSignatureIsSet(true);
      }
      if (incoming.get(2)) {
        struct.pnKey = iprot.readString();
        struct.setPnKeyIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

