package com.doubleclue.dcem.as.comm.client;

public enum AsErrorCodes {
    OK(0),
    SDKCONFIG_NOTFOUND(1),
    CONFIGURE_HOME_DIRECTORY(2),
    SDKCONFIG_READ_ERROR(3),
    SDKSETTINGS_READ_ERROR(4),
    WRITING_SERIALIZING_FILE(5),
    SERIALIZING_OBJECT(6),
    READING_DESIRIALIZING_FILE(7),
    DESIRIALIZING_OBJECT(8),
    CONNECTION_FAIL(9),
    COULDNOT_SAVE_SETTINGS(10),
    COULDNOT_CREATE_CSR(11),
    CHIPER_FAILURE(12),
    WRONG_SERVER_SIGNATURE(13),
    GENERIC(14),
    INVALID_STATE(15),
    SIGNING_FAILED(16),
    PASSWORD_DECRYPTION_FAILED(17),
    FINGERPRINT_FAILED(18),
    RES4(19),
    ACTION_BUTTON_WO_ID(20),
    SENDING_QRCODE_FAILED(21),
    INVALID_SDK_CONFIG(22),
    INVALID_TRUSTSTORE_FORMAT(23),
    SERVER_RESPONSE_ERROR(24),
    SECURE_CONNECTION_FAIL(25),
    PASSWORD_TOO_SHORT(26),
    ACTIVATION_CODE_EMPTY(27),
    USERID_EMPTY(28),
    PASSWORD_EMPTY(29),
    DEVICE_NAME_EMPTY(30),
    UNKNOWN_PLATFORM(31),
    SERVER_BUSY(32),
    NO_LIB_VERSION(33),
    CONNECTION_IS_CLOSED(34),
    COULD_NOT_RETREIVE_TEMPLATE(35),
    APP_MSG_TIMEDOUT(36),
    INVALID_INPUT_DATA_FORMAT(37),
    INVALID_PROPERTY_HOME_DIRECTORY(38),
    INVALID_PARAMETER(39),
    USER_NOT_EXISTS(40),
    NO_USER_EXISTS(41),
    INVALID_USER(42),
    UNSUPPORTED_PLATFORM(43),
    CURRENT_PASSWORD_TOO_SHORT(44),
    NEW_PASSWORD_INVALID(45),
    PASSWORDS_ARE_IDENTIC(46),
    PASSWORD_CONFIRM_INVALID(47),
    UNKNOWN_FILE_IN_CONFIG(48),
    MISSING_FILE_IN_CONFIG(49),
    CORRUPTED_SDKCONFIG(50),
    PROXY_HOSTNAME_EMPTY(51),
    PROXY_PORT_EMPTY(52),
    PROXY_PORT_NO_NUMBER(53),
    USER_ALREADY_ACTIVATED(54),
    SECURE_CONNECTION_UNTRUSTED(55), SECURE_CONNECTION_INVALID_HOST_NAME (56);



    int errorCode;

    AsErrorCodes(int errorCode) {
        this.errorCode = errorCode;
    }

    public int getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

}
